### ISSUE TITLE
Brainflow Streaming problem, OpenBCI Cyton with Wifi-shield

### ISSUE THREAD

**Issue by stella185** [brainflow-dev/brainflow#390]
**Describe the bug**
I cannot stream my EEG data to Pycharm 
**To Reproduce**
To report a bug you need to create a simple example that uses only BrainFlow API or use one of the tests we already have.  In this example, you need to call `enable_dev_board_logger ()` and share the output with us. Also, make sure the latest version is used. 

**Info (please complete the following information):**
 - Board Id: 5
 - OS running on your PC: Windows 10
 - Programming Language and its version Python 3.9
 - Architecture(x86, x64, ARM, etc)
 - In case of Python full output of `pip list` command, for other languages please provide BrainFlow version used
BrainFlow 4.7.0
**Expected behavior**
PycharmProjects\OpenBCI\venv\Scripts\python.exe C:/Users/jacky/PycharmProjects/OpenBCI/brianflow.py --board-id 5 --ip-address 192.168.1.100 --ip-protocol 2 --ip-port 16580
[2021-11-21 21:58:41.131] [board_logger] [info] incoming json: {
    "file": "",
    "ip_address": "192.168.1.100",
    "ip_port": 16580,
    "ip_protocol": 2,
    "mac_address": "",
    "other_info": "",
    "serial_number": "",
    "serial_port": "",
    "timeout": 0
}
[2021-11-21 21:58:41.131] [board_logger] [trace] Board object created 5
[2021-11-21 21:58:41.131] [board_logger] [info] use 10 as http timeout
[2021-11-21 21:58:41.133] [board_logger] [info] local ip addr is 192.168.1.101
[2021-11-21 21:58:41.133] [board_logger] [trace] bind socket, port  is 16580
[2021-11-21 21:58:41.134] [board_logger] [trace] recieved 0 bytes
[2021-11-21 21:58:43.181] [board_logger] [trace] recieved 96 bytes
[2021-11-21 21:58:43.196] [board_logger] [trace] response data {"board_connected":true,"board_type":"cyton","num_channels":8,"gains":[24,24,24,24,24,24,24,24]}
[2021-11-21 21:58:43.197] [board_logger] [info] configuration string {"delimiter":true,"ip":"192.168.1.101","latency":10000,"output":"raw","port":16580}
[2021-11-21 21:58:43.197] [board_logger] [trace] recieved 0 bytes
[2021-11-21 21:58:45.295] [board_logger] [trace] recieved 100 bytes
[2021-11-21 21:58:45.310] [board_logger] [trace] response data {"connected":true,"delimiter":true,"ip":"192.168.1.101","output":"raw","port":16580,"latency":10000}
[2021-11-21 21:58:45.311] [board_logger] [trace] waiting for accept 0/10
[2021-11-21 21:58:45.311] [board_logger] [trace] connected
[2021-11-21 21:58:45.311] [board_logger] [info] command string {"command":"~4"}
[2021-11-21 21:58:45.311] [board_logger] [trace] recieved 0 bytes
[2021-11-21 21:58:47.417] [board_logger] [trace] recieved 32 bytes
[2021-11-21 21:58:47.432] [board_logger] [trace] response data Success: Sample rate is 1000Hz

[2021-11-21 21:58:47.433] [board_logger] [warning] If you change gain you may need to rescale EXG data
[2021-11-21 21:58:47.433] [board_logger] [info] command string {"command":"d"}
[2021-11-21 21:58:47.433] [board_logger] [trace] recieved 0 bytes
[2021-11-21 21:58:49.594] [board_logger] [error] request failed
Traceback (most recent call last):
  File "C:\Users\jacky\PycharmProjects\OpenBCI\brianflow.py", line 57, in <module>
    main()
  File "C:\Users\jacky\PycharmProjects\OpenBCI\brianflow.py", line 43, in main
    board.prepare_session()
  File "C:\Users\jacky\PycharmProjects\OpenBCI\venv\lib\site-packages\brainflow\board_shim.py", line 896, in prepare_session
    raise BrainFlowError('unable to prepare streaming session', res)
brainflow.board_shim.BrainFlowError: BOARD_WRITE_ERROR:4 unable to prepare streaming session

**Screenshots**

**Additional context**

**Comment by Andrey1994** [comment]
Hi, do you see it always or sometimes? I dont think that its a problem with brainflow and more likely cannot be solved in software...
You can try to comment out this line https://github.com/brainflow-dev/brainflow/blob/master/src/board_controller/openbci/cyton_wifi.cpp#L26 and build from the source
