### ISSUE TITLE
Connection Issues with Ganglion on Mac

### ISSUE THREAD

**Issue by mgroth0** [brainflow-dev/brainflow#520]
**Describe the bug**

This is the same issue that I asked about in slack a while ago (sorry for the long absence). The connection to the device sometimes works, sometimes doesn't. A few observations:

- Usually works the first time
- Usually does not work the second time, but sometimes it does. There are no 100% reliable patterns
- Usually requires turning the ganglion off, turning the Mac's bluetooth off, and waiting for a bit to make it work (though even this is not 100% reliable)
- Sometimes the blue light becomes solid but the code still fails.
- Before the code begins, the blue light on the Ganglion is blinking. When the connection is made and data is streaming, the blue light is solid. After the code ends, the blue light _stays solid_ (does this mean it did not properly disconnect or something?)
- It is very infrequent that the code runs without error. Like 1/20 times maybe. Or maybe I'm just not waiting long enough between attempts. Waiting for a few min seems to increase the chances it will work by a lot.

**To Reproduce**

Machine: M1 Mac with Mac OS 12.4
OpenBCI Ganglion Board
Brainflow 5.0.1

I have an M1 mac and an OpenBCI Ganglion. I'm running this test code with the java package:

``` kotlin
fun main() {
  BoardShim.enable_dev_board_logger()
  val params = BrainFlowInputParams()
  params.serial_port = "/dev/cu.usbmodem11"
  val board_id = BoardIds.GANGLION_BOARD._code
  val board_shim = BoardShim(board_id, params)
  println("preparing session")
  board_shim.prepare_session()
  println("session prepared")
  board_shim.start_stream(450000, "")
  println("started stream")
  BoardShim.log_message(LEVEL_INFO._code, "Start sleeping in the main thread")
  Thread.sleep(5000)
  board_shim.stop_stream()
  println(board_shim._board_data_count)
  val data = board_shim.get_current_board_data(30) // doesnt flush it from ring buffer
  for (i in data.indices) {
	println(Arrays.toString(data[i]))
  }
  board_shim.release_session()
  exitProcess(0)
}
```

**Output On Successful Run**
```
file: libsimpleble-c.dylib is not found in jar file
file: libBrainFlowBluetooth.dylib is not found in jar file
preparing session
[2022-07-06 19:21:02.588] [board_logger] [info] incoming json: {"ip_address":"","mac_address":"","serial_port":"/dev/cu.usbmodem11","ip_port":0,"ip_protocol":0,"other_info":"","timeout":0,"serial_number":"","file":""}
[2022-07-06 19:21:02.589] [board_logger] [debug] use dyn lib: /Users/matthewgroth/Library/Caches/JNA/temp/libGanglionLib.dylib
[2022-07-06 19:21:02.589] [board_logger] [trace] Board object created 1
[2022-07-06 19:21:02.662] [board_logger] [debug] Library is loaded
[2022-07-06 19:21:02.662] [board_logger] [info] use 15 as a timeout for device discovery and for callbacks
[2022-07-06 19:21:02.662] [board_logger] [debug] ganglionlib initialized
[2022-07-06 19:21:02.662] [board_logger] [info] mac address is not specified, try to find ganglion without it
session prepared
[2022-07-06 19:21:12.950] [board_logger] [debug] use stub streamer
[2022-07-06 19:21:12.950] [board_logger] [info] use command b to start streaming
started stream
[2022-07-06 19:21:13.118] [board_logger] [info] Start sleeping in the main thread
[2022-07-06 19:21:13.118] [board_logger] [debug] start streaming
412
[137.0, 137.0, 142.0, 142.0, 143.0, 143.0, 144.0, 144.0, 145.0, 145.0, 146.0, 146.0, 148.0, 148.0, 149.0, 149.0, 150.0, 150.0, 151.0, 151.0, 152.0, 152.0, 155.0, 155.0, 161.0, 161.0, 162.0, 162.0, 163.0, 163.0]
[-2581.084474619478, -2672.915848081466, -2877.364958959166, -2963.1189949931577, -3429.1030496722087, -3507.6783477412537, -3730.8849268467166, -3462.3825494279154, -3898.2865887633525, -3596.080232943874, -3192.7095833229832, -3659.6323528909124, -4134.012482970487, -4213.077707933728, -4445.207688333467, -4152.597915800288, -4588.68895013351, -4311.955052912235, -3894.4176622591913, -4354.238361811265, -4543.952266863547, -4641.1578765618615, -5095.682877776679, -4806.801785499323, -4387.910551062319, -4858.805094383191, -5046.84726415528, -5143.140338264406, -5610.36229982879, -5678.241484024562]
[-3494.566258496605, -3602.8270124639384, -3802.275877100881, -3904.03294504527, -4370.334891220555, -4426.410951156169, -4675.333082356956, -4392.68266340578, -4827.498391854111, -4533.209404240828, -4139.958923900034, -4590.220439165365, -5058.190380720887, -5101.670457605738, -5364.362900443375, -5083.429095571861, -5497.630495464429, -5232.733381602913, -4829.033620785922, -5270.3455554572865, -5469.47278869804, -5569.053234868217, -5992.765200348105, -5718.2789830002, -5321.860807396937, -5773.984792840201, -5967.023468953092, -6072.78970964998, -6535.579889766872, -6569.594279863872]
[1440.6524717812426, 1340.7653538146988, 1183.8840304734185, 1087.0224915710278, 1565.8400129480287, 1513.7656459650025, 1294.3924643141218, 1538.1628833259456, 1097.2511179498397, 1431.590694188606, 1824.5457224329002, 2307.4098155619577, 2776.5222965539433, 2747.5044127977453, 2510.673378153704, 2762.9745089644566, 2327.0368105294183, 2642.2954171942547, 3039.798163784668, 2554.561104133725, 2402.911900830455, 2304.6591191445477, 1858.885483826045, 2179.7651601242833, 2568.000434624497, 2078.2717551267706, 1926.7571882219054, 1826.2417670628056, 2312.011762457434, 2265.726760605816]
[1332.7376585598104, 1260.8287321617827, 1082.8169740708545, 1009.7449387866072, 1498.9182431409135, 1415.2267619324848, 1206.613272454124, 1487.4834990263917, 1012.3217298560776, 1338.6242610900663, 1753.1098933792673, 1264.8322950643487, 1753.7699857214466, 1682.5024521658197, 1465.5602054861374, 1746.7857225541957, 1290.1065389649011, 1595.7049840441905, 2024.585491262842, 2505.2542631179094, 2328.0353638175875, 2245.572439744603, 1772.2993200519122, 2081.547907487955, 2492.0318468245678, 2979.6530926972628, 2799.345036033541, 2727.634324333165, 2245.5537402448244, 2171.312986224424]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.657149677764969E9, 1.657149677764969E9, 1.657149677788961E9, 1.657149677788961E9, 1.657149677813363E9, 1.657149677813363E9, 1.657149677836941E9, 1.657149677836941E9, 1.657149677861181E9, 1.657149677861181E9, 1.657149677884939E9, 1.657149677884939E9, 1.657149677908946E9, 1.657149677908946E9, 1.657149677932948E9, 1.657149677932948E9, 1.657149677958912E9, 1.657149677958912E9, 1.657149677981976E9, 1.657149677981976E9, 1.657149678005909E9, 1.657149678005909E9, 1.657149678029871E9, 1.657149678029871E9, 1.657149678053861E9, 1.657149678053861E9, 1.657149678077889E9, 1.657149678077889E9, 1.657149678101869E9, 1.657149678101869E9]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

**Output On Failure Run**
```
file: libsimpleble-c.dylib is not found in jar file
file: libBrainFlowBluetooth.dylib is not found in jar file
preparing session
[2022-07-06 19:23:16.869] [board_logger] [info] incoming json: {"ip_address":"","mac_address":"","serial_port":"/dev/cu.usbmodem11","ip_port":0,"ip_protocol":0,"other_info":"","timeout":0,"serial_number":"","file":""}
[2022-07-06 19:23:16.869] [board_logger] [debug] use dyn lib: /Users/matthewgroth/Library/Caches/JNA/temp/libGanglionLib.dylib
[2022-07-06 19:23:16.869] [board_logger] [trace] Board object created 1
[2022-07-06 19:23:16.891] [board_logger] [debug] Library is loaded
[2022-07-06 19:23:16.891] [board_logger] [info] use 15 as a timeout for device discovery and for callbacks
[2022-07-06 19:23:16.891] [board_logger] [debug] ganglionlib initialized
[2022-07-06 19:23:16.891] [board_logger] [info] mac address is not specified, try to find ganglion without it
[2022-07-06 19:23:34.359] [board_logger] [error] failed to Open Ganglion Device 15
Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: brainflow.BrainFlowError: Error in prepare_session:GENERAL_ERROR
	at brainflow.BoardShim.prepare_session(BoardShim.java:883)
	at matt.eeg.simplified.SimplifiedKt.main(simplified.kt:18)
     [excluding rest of stack trace]
in uncaughtException for java.lang.RuntimeException: Exception in Application start method
got exception: RuntimeException: Exception in Application start method
caused by: BrainFlowError: Error in prepare_session:GENERAL_ERROR
trying to format 1107296256
trying to format 32212254720
trying to format 1056159504
trying to show exception dialog
in extraShutdownHook
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: brainflow.BrainFlowError: Error in prepare_session:GENERAL_ERROR
	at brainflow.BoardShim.prepare_session(BoardShim.java:883)
	at matt.eeg.simplified.SimplifiedKt.main(simplified.kt:18)
	[excluding rest of stack trace]
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: brainflow.BrainFlowError: Error in prepare_session:GENERAL_ERROR
	at brainflow.BoardShim.prepare_session(BoardShim.java:883)
	at matt.eeg.simplified.SimplifiedKt.main(simplified.kt:18)
```

**Note on previous discussion**

On slack it was suggested that I look at https://github.com/brainflow-dev/brainflow/pull/431. Sorry again, I took a very long time to look at it. I copied and pasted the changes to `src/board_controller/openbci/ganglion_bglib/main.cpp` and `src/board_controller/openbci/ganglion_bglib/callbacks.cpp` and rebuilt the java package so I could test it. These changes seemed to produce even more errors than before, so I reverted back to the regular code.

**Comment by Andrey1994** [comment]
yes, and its the reason why they are not merged... and it works worse only for mac
actually you issue means that device doesnt send advertising packages and cannot be discovered, and I have no idea why
